path:
  wx: E:\WeChat\WeChat.exe
  idea: D:\idea64.exe.lnk
  wst: D:\webstorm64.exe-shortcut.lnk
  scp: D:\WinSCP\WinSCP.exe
  tp: D:\Typora\Typora.exe
  vpn: E:\Clash.for.Windows-0.20.16-win\Clash
  bs: D:\chrome.lnk
  chrome: D:\chrome.lnk
  edge: D:\Edge.lnk
  draw: D:\draw.io\draw.io.exe
  uml: C:\Program Files\StarUML\StarUML.exe
  snip: D:\Snipaste-2.8.7-Beta-x86\Snipaste.exe
  store: D:\Nutstore_spe\Nutstore\Nutstore.exe
  ms: E:\foobar\foobar2000.exe
  net: C:\Users\Public\Desktop\Dr.COM.lnk
  wps: E:\ksolaunch.exe.lnk
  fs: E:\Feishu\Feishu.exe
  qq: E:\QQ\QQ.exe
  calc: calc
  tv: E:\bilibili\bilibili.exe
  code: D:\Code_shortcut.exe.lnk
  startwork: D:/redis/work-starter.bat
  py: D:\py_shortcut.lnk
  nacos: e:\work_copilot\quick_start\start_nacos.bat
  sentinel: E:\Sentinel\start_sentinel.cmd
  jmeter: E:\jmeter-5.6.3\bin\jmeter.bat
  seata: E:\seata\apache-seata-2.2.0-incubating-bin\seata-server\bin\seata-server.bat

version:
  version: 3.0.0
  name: work-copilot
  author: lingojack
  email: lingojack@qq.com
  mode: normal  # normal | strategy

log:
  mode: concise   # verbose | concise

inner_url:
  zhihu: www.zhihu.com
  email: wx.mail.qq.com
  ct: omofuns.top
  tsl: https://www.deepl.com/zh/translator

outer_url:
  gpt: chatgpt.com
  github: github.com

editor:
  idea: D:\IntelliJ_IDEA_2023.2.2\bin\idea64.exe
  wst: D:\WebStorm_2023.3.4\bin\webstorm64.exe
  tp: D:\Typora\Typora.exe
  wps: E:\ksolaunch.exe.lnk
  code: D:\Microsoft_VS_Code\Code.exe
  ms: E:\foobar\foobar2000.exe

browser:
  bs: D:\chrome.lnk
  chrome: D:\chrome.lnk
  edge: D:\Edge.lnk

vpn:
  vpn: E:\Clash.for.Windows-0.20.16-win\Clash

report:
  week_report: D:\markdown_notebook\week_report.md
  week_num: 54
  last_day: 2024.11.20

storage:
  mode: config  # config | db
  config:
    path:
  db:
    type: mysql
    username:
    password:
