editor:
  tp: /Applications/Typora.app
  idea: /Applications/work_copilot_java/link/idea.app
  code: /Applications/work_copilot_java/link/code.app
color:
  warn: null
  error: null
  log: null
  info: null
log:
  mode: concise
storage:
  mode: config
  config:
    path: null
  db:
    type: mysql
    password: null
    username: null
inner_url:
  suixianglu: https://www.programmercarl.com/
  bl: https://www.bilibili.com/
version:
  name: work-copilot
  mode: normal
  version: 5.0.0
  author: lingojack
  email: lingojack@qq.com
script:
  open-copilot: /Applications/work_copilot_java/script/open-copilot.sh
  depot: /Applications/work_copilot_java/script/
  download-bv: /Applications/work_copilot_java/script/download-bv.sh
  open-report: /Applications/work_copilot_java/script/open-report.sh
  ip: /Applications/work_copilot_java/script/ip.sh
  leetcode: /Applications/work_copilot_java/script/leetcode.sh
  push-report: /Applications/work_copilot_java/script/push-report.sh
  pull-report: /Applications/work_copilot_java/script/sync-report.sh
setting:
  search-engine: bing
path:
  qq: /Applications/QQ.app
  wx: /Applications/WeChat.app
  code: /Applications/work_copilot_java/link/code.app
  idea: /Applications/work_copilot_java/link/idea.app
  ms: /Applications/foobar2000.app
  open-report: /Applications/work_copilot_java/script/open-report.sh
  ip: /Applications/work_copilot_java/script/ip.sh
  leetcode: /Applications/work_copilot_java/script/leetcode.sh
  landrop: /Applications/LANDrop.app
  fs: /Applications/Lark.app
  open-copilot: /Applications/work_copilot_java/script/open-copilot.sh
  bs: /Applications/work_copilot_java/link/chrome.app
  vpn: /Applications/SFM.app
  download-bv: /Applications/work_copilot_java/script/download-bv.sh
  snip: /Applications/Snipaste.app
  calc: /System/Applications/Calculator.app
  wps: /Applications/work_copilot_java/link/wps
  tp: /Applications/Typora.app
  push-report: /Applications/work_copilot_java/script/push-report.sh
  pull-report: /Applications/work_copilot_java/script/sync-report.sh
vpn:
  vpn: /Applications/SFM.app
browser:
  bs: /Applications/work_copilot_java/link/chrome.app
report:
  week_num: '59'
  week_report: /Applications/work_copilot_java/report/week_report.md
  last_day: 2024.12.11
outer_url:
  gpt: https://chatgpt.com/
  github: https://github.com/
