editor: null
color:
  warn: null
  error: null
  log: null
  info: null
log:
  mode: concise
inner_url: null
storage:
  mode: config
  config:
    path: null
  db:
    type: mysql
    password: null
    username: null
version:
  name: work-copilot
  mode: normal
  version: 5.0.0
  author: lingojack
  email: lingojack@qq.com
script: null
setting:
  search-engine: bing
path:
  bs: /Applications/work_copilot_java/link/chrome.app
vpn: null
browser:
  bs: /Applications/work_copilot_java/link/chrome.app
report:
  week_num: '58'
  week_report: /Users/a1-6/Documents/markdown_notebook/week_report.md
  last_day: 2024.12.04
outer_url: null
