editor:
  code: /Applications/work_copilot_java/link/code.app
  wps: /Applications/work_copilot_java/link/wps
  tp: /Applications/Typora.app
  idea: /Applications/work_copilot_java/link/idea.app
color:
  warn: null
  error: null
  log: null
  info: null
log:
  mode: concise
inner_url:
  suixainglu: https://www.programmercarl.com/
storage:
  mode: config
  config:
    path: null
  db:
    type: mysql
    password: null
    username: null
version:
  name: work-copilot
  mode: normal
  version: 5.0.0
  author: lingojack
  email: lingojack@qq.com
script:
  depot: /Applications/work_copilot_java/script/
  leetcode: /Applications/work_copilot_java/script/leetcode.sh
  download-bv: /Applications/work_copilot_java/script/download-bv.sh
setting:
  search-engine: bing
path:
  wx: /Applications/WeChat.app
  code: /Applications/work_copilot_java/link/code.app
  idea: /Applications/work_copilot_java/link/idea.app
  ms: /Applications/foobar2000.app
  leetcode: /Applications/work_copilot_java/script/leetcode.sh
  landrop: /Applications/LANDrop.app
  fs: /Applications/Lark.app
  bs: /Applications/work_copilot_java/link/chrome.app
  vpn: /Applications/SFM.app
  download-bv: /Applications/work_copilot_java/script/download-bv.sh
  snip: /Applications/Snipaste.app
  wps: /Applications/work_copilot_java/link/wps
  calc: /System/Applications/Calculator.app
  tp: /Applications/Typora.app
vpn:
  vpn: /Applications/SFM.app
browser:
  bs: /Applications/work_copilot_java/link/chrome.app
report:
  week_num: '58'
  week_report: /Applications/work_copilot_java/report/week_report.md
  last_day: 2024.12.04
outer_url:
  gpt: https://chatgpt.com/
